# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170324_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricetta',
            name='img_url',
        ),
        migrations.AddField(
            model_name='ricetta',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='ricette_images'),
        ),
    ]
