# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20170325_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('preparation_time_min', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(1)])),
                ('like', models.IntegerField(default=0)),
                ('preparation', models.CharField(max_length=500)),
                ('image', models.ImageField(default='media/default.jpg', upload_to='recipe_images')),
            ],
        ),
        migrations.RenameModel(
            old_name='Sottocategoria',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Commento',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Ingrediente',
            new_name='Subcategory',
        ),
        migrations.AlterUniqueTogether(
            name='ingredientericetta',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ingredientericetta',
            name='id_ingrediente',
        ),
        migrations.RemoveField(
            model_name='ingredientericetta',
            name='id_ricetta',
        ),
        migrations.RemoveField(
            model_name='ricetta',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='ricetta',
            name='id_sottocategoria',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='descrizione',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id_ricetta',
        ),
        migrations.DeleteModel(
            name='IngredienteRicetta',
        ),
        migrations.DeleteModel(
            name='Ricetta',
        ),
        migrations.AddField(
            model_name='recipe',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='id_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Subcategory'),
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='id_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='id_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Recipe'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Recipe'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ingredientrecipe',
            unique_together=set([('id_recipe', 'id_ingredient')]),
        ),
    ]
