# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20170325_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='like',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(0)]),
        ),
    ]
