# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20170325_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='like',
        ),
    ]
