# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20170329_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=models.CharField(max_length=5000),
        ),
    ]
