# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20170330_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ingredientrecipe',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='id_ingredient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
