# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20170331_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='recipe_images'),
        ),
    ]
